### ISSUE TITLE
ImageVariable -> Add InputStream support constructor

### ISSUE THREAD

**Issue by gibbonsj** [jsolve/templ4docx#24]
Add InputStream support constructor allowing a broader range of image stream for replacements including those from in-memory data (e.g. Byte array).

**Comment by gibbonsj** [comment]
Recommending as 2.X milestone and closing issue

**Comment by lstypka** [comment]
@gibbonsj  Thank you for your contributing to templ4docx. Your pullRequest has been accepted and new version of templ4docx has been released: ***2.0.1***

Once again: Thank you!
