### ISSUE TITLE
Replace variable in header and footer

### ISSUE THREAD

**Issue by diufanman** [jsolve/templ4docx#34]
Is it possible to replace the variables in header and footer, I tried your example but only replace the variables in the content but not header and footer.

**Comment by mangelo123** [comment]
Is there a solution to this? I just tried replacing text in a footer and it does not work.

**Comment by tnguyen512** [comment]
I have the same issue

**Comment by youngyou** [comment]
Maybe try my fork, branch `header_footer_support`.
It works for me, but I didn't test it fully.
Maybe a PR later.

**Comment by fjloma** [comment]
Please, any update on this ?

**Comment by shakthifuture** [comment]
Same issue for me, Header and footer replacing not working.
